### GET alluser

GET http://localhost:5555/user

### CREATE user

POST  http://localhost:5555/user
Content-Type: application/json

{
    "pseudo":"Tommy",
    "password":"tommy",
    "email":"tommy@gmail.com"

}